### ISSUE TITLE
Authentication is disabled

### ISSUE THREAD

**Issue by qoh** [BlocklandGlass/GlassWebsite#27]
The website does not appear to make any effort to make sure users are who they claim to be. See `attemptBlocklandAuth`: https://github.com/BlocklandGlass/GlassWebsite/blob/da88c0435a0fdde438b0fea1b54cb447289b537c/api/2/private/ClientConnection.php#L65

As a consequence, the `/api/2/auth.php` endpoint always accepts what you give it. For example, `?username=&blid=evil` gives you a perfectly valid token for those parameters, as Glass Live can confirm:

```javascript
{ type: 'roomUserJoin',
  id: 0,
  username: '',
  blid: 'evil',
  admin: false,
  mod: false,
  online: true,
  status: 'hidden',
  icon: 'user' }
```

This further affects things such as verification of website accounts. As several parts of the site blindly trust things like stored usernames, that could open you up to XSS (you seem to use CSRF tokens in quite a few places which mitigates it however). Here's a user profile with an invalid BLID (`is_numeric` in `/ajax/register.php` is not for BLIDs) and a username of `<script>alert('hi')</script>`, which **executes JavaScript code for anybody viewing it**:

https://blocklandglass.com/user/view.php?blid=-5

You were likely already aware of this, but in any case, I don't think you should even be allowing registrations (if even leaving the parts service that use auth up) while this is still an issue.

**Comment by qoh** [comment]
As an example of a proper implementation (I think you disabled it due to issues with special characters?), Pecon asked me to point you to https://forum.blockland.us/index.php?topic=303719

**Comment by dpendic** [comment]
Thanks for pointing this out, I believe I bypassed it when I was attempting to fix other special character auth issues and just never undid it. The actual auth, should it work, uses Pecon's BlocklandAuthenticate method.

I'll be more thorough with displaying and trusting database information. The site is not made well at all.
