### ISSUE TITLE
Issue with markdown

### ISSUE THREAD

**Issue by McTwist** [BlocklandGlass/GlassWebsite#39]
There is an issue with certain markdown text. [Link](https://blocklandglass.com/addons/addon.php?id=945)

![bug](https://user-images.githubusercontent.com/614764/44309375-f50db080-a3c5-11e8-82a9-3f8fe6a5809f.png)

**Comment by ShockFromBL** [comment]
710c7471cd3985ff8c31b844c07b872b25f6ae2a
