### ISSUE TITLE
Add setClipboard when retrieving the Discord key

### ISSUE THREAD

**Issue by McTwist** [BlocklandGlass/GlassWebsite#41]
Currently you need to insert the key manually by having both the Discord window open together with the Blockland window and type manually.

Adding `setClipboard` function will make it easier to just copy the piece of validation code and paste it to GlassBot.

**Comment by ShockFromBL** [comment]
This belongs in BlocklandGlass not GlassWebsite.

https://github.com/BlocklandGlass/BlocklandGlass/issues/new

**Comment by McTwist** [comment]
Ops. My bad. I opened the issue there now.
